{
    "type": "bundle",
    "id": "bundle--ca31afe1-d6eb-4dae-858d-247071456dcd",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--fc69a79f-916a-4a1a-8eca-3bd95ca92251",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:12:26.748313Z",
            "modified": "2021-03-13T20:12:26.748313Z",
            "name": "CVE-2020-15801",
            "description": "In Python 3.8.4, sys.path restrictions specified in a python38._pth file are ignored, allowing code to be loaded from arbitrary locations. The <executable-name>._pth file (e.g., the python._pth file) is not affected.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2020-15801"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}