{
    "type": "bundle",
    "id": "bundle--8fe9ce71-0351-42f8-bba1-9dcaef32e08b",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ca3cdcb8-fe00-4183-a00a-68ea2626fe68",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:50.353057Z",
            "modified": "2021-03-13T20:11:50.353057Z",
            "name": "CVE-2019-14491",
            "description": "An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2019-14491"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}