{
    "type": "bundle",
    "id": "bundle--79dc16e8-a994-42d5-9a93-d399cb82e75e",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--5bab4467-99ea-44c3-8966-69c480819252",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:54.220953Z",
            "modified": "2021-03-13T20:11:54.220953Z",
            "name": "CVE-2019-10212",
            "description": "A flaw was found in, all under 2.0.20, in the Undertow DEBUG log for io.undertow.request.security. If enabled, an attacker could abuse this flaw to obtain the user's credentials from the log files.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2019-10212"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}