{
    "type": "bundle",
    "id": "bundle--02c8e122-3dac-469d-aa1d-4a2ff019b47d",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--74da8436-cb8b-469a-a97b-f0a6a54bd075",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:15.716258Z",
            "modified": "2021-03-13T20:11:15.716258Z",
            "name": "CVE-2017-9162",
            "description": "libautotrace.a in AutoTrace 0.31.1 has a \"cannot be represented in type int\" issue in autotrace.c:191:2.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2017-9162"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}