{
    "type": "bundle",
    "id": "bundle--411619df-5795-4345-94bf-f6d3af22d782",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--4fca6341-32d0-43d6-a1a1-8e6ca065d2a7",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:59.854208Z",
            "modified": "2021-03-13T20:11:59.854208Z",
            "name": "CVE-2019-16226",
            "description": "An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node->mn_hi, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2019-16226"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}