{
    "type": "bundle",
    "id": "bundle--456e12a2-8060-4db0-b469-3661291657f2",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--92baa352-ec98-4947-b195-494221663b76",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:53.320784Z",
            "modified": "2021-03-13T20:11:53.320784Z",
            "name": "CVE-2019-9948",
            "description": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2019-9948"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}