{
    "type": "bundle",
    "id": "bundle--e6f781f6-52a4-43fe-b171-ed30e3f74d59",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--62b0e557-0b50-4819-8fe0-d4bee9fae67e",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:15.845927Z",
            "modified": "2021-03-13T20:11:15.845927Z",
            "name": "CVE-2017-9197",
            "description": "libautotrace.a in AutoTrace 0.31.1 has a \"cannot be represented in type int\" issue in input-tga.c:498:55.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2017-9197"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}