{
    "type": "bundle",
    "id": "bundle--dbaa993d-1a00-42ad-abae-d87cf3b6be5a",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ebebe9fb-75c8-46f3-80e5-3c7ae11a1d5d",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:59.807263Z",
            "modified": "2021-03-13T20:11:59.807263Z",
            "name": "CVE-2019-16877",
            "description": "Portainer before 1.22.1 has Incorrect Access Control (issue 4 of 4).",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2019-16877"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}