{
    "type": "bundle",
    "id": "bundle--aa236783-fe6b-492c-9463-52a374618a7c",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--801151b2-b616-442a-9b15-cb520d30ed61",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-03-13T20:11:49.483934Z",
            "modified": "2021-03-13T20:11:49.483934Z",
            "name": "CVE-2019-15032",
            "description": "Pydio 6.0.8 mishandles error reporting when a directory allows unauthenticated uploads, and the remote-upload option is used with the http://localhost:22 URL. The attacker can obtain sensitive information such as the name of the user who created that directory and other internal server information.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2019-15032"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}